"""The code map (docs/CODEMAP.md), generated from the code: every charkit module's docstring opening and its public
functions and classes with their first docstring lines, the QA parts the registry holds (name, order, prefix, module),
the command line's commands, the calibration entries and declared checks per module, under a short curated header
(where the builders, QA parts, calibration, simulation, renderer and gate live). Read with ast: nothing is imported,
so it runs in a second and reads any tree. Deterministic: the same tree gives the same file (sorted, no dates).
Code reading took 4.4 h of the agents' time on 2026-09-30 (charkit/out/audit/20260930); this is the index to start
from.

    python -m charkit.codemap [--out docs/CODEMAP.md] [--root TREE] [--check]
        --check: exit 1 when the file differs from what the tree generates (it never fails a gate: the map is
        regenerated, not enforced)
"""
import ast, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join('docs', 'CODEMAP.md')
PACKAGES = ('', 'geom', 'render', 'sim', 'calib', 'steps', 'boards', 'styles')
SKIP = ('out', 'tests', '__pycache__', 'assets', 'refs', 'spec', 'accepted')
FIRST = 360                  # characters of a module docstring's opening kept
LINE = 118                   # characters of a function's first docstring line kept

HEADER = """# charkit code map

Generated by `python -m charkit.codemap` from the code (docstrings, public names, the QA registry, the command line);
regenerate it after changing a module's docstring or public functions. The curated part is this header; everything below
"## Modules" is generated. Usage lives in each module's docstring: read it before the code.

## Where things live

- **The build** (`python -m charkit build`, charkit/cli.py): the spec resolved (manifest.py, refs.py), the venv steps
  (cli.code_head, code_body, geom_hair, hair_select, pieces_hair, garments_geom: each a cache.file_step), then Blender
  (build_blender.py drives scene.py's stages: character.py assembles the head and body, hair, garments, shading), the
  geometry bundle (bundle.py), the QA (qa3d.run), the boards, the look export (gltf.py). The cache: cache.py.
- **Builders** (Blender side and their venv twins): character.py, head.py, code_base.py (the authored head),
  code_body.py / body.py (the body), hair.py, geom/hairpieces.py (the hair pieces), garments.py and outfit.py (the
  outfit), accessories.py, eyes.py, mouth.py, expressions.py, shade.py / faceshade.py (materials, face shading),
  geomstage.py (the garments' venv stage), base_anime.py (the anime base mesh).
- **Fast evaluators and fits**: bodyeval.py (numpy body, garments, hair: the sweep's garments stage), faceeval.py,
  fitkit.py, bodyfit.py, facefit.py, tune.py, triage.py, hairlab.py (the hair pieces rebuilt and measured).
- **QA parts**: registered with `@qa_part` (registry.py; table below), run by qa3d.run on a bundle. Shape IoU per
  piece and view: qa3d.sheet_pieces (piece_*), qa3d.hair_pieces (hair_piece_*). Flag checks carry `flag`
  (registry.flag_check). Declared checks (a family, a piece, limits): declared.py. Measurement steps: steps/*.py.
- **Calibration**: calibrate.py (the triple: design moved 1-2 px, known-bad, random floor; records in
  calib/records), the stand-ins in calib/*.py (labels.Garments, details.Details, ...), declared.Declared (generic).
- **Variants and attribution**: sweep.py (`charkit sweep`: declared rows rebuilt at a stage, measured, tabulated with
  the shape guard; swap mode); optimize.py (`charkit sweep optimize`: a fit's knobs tuned by CMA-ES over sweep rows on
  persistent workers, the constraints enforced, the best confirmed by real builds).
- **Gate and infrastructure**: gate.py (policy K), pregate.py, codediff.py, closure.py, history.py, remote.py and
  boxjob.py (the boxes), bucketsync.py, procs.py (build slots), worker.py, sparse.py, trace.py, profile.py (a build's
  wall and CPU by stage, the QA's parts under cProfile; the build-CPU budget, charkit/budget.json).
- **Review pages**: reviewpage.py (`charkit review page`: the standard page), preview.py (per-merge previews),
  review.py, flags.py, checkpoint.py, *page.py.
- **Simulation**: sim/ (xpbd.py cloth, springbone.py, drape.py, motion.py, motionqa.py).
- **Renderer**: render/ (charkit's WebGPU toon renderer: gpu.py, buffers.py, views.py, softras.py, parity.py);
  qarender.py (the QA's drawing through it).
- **Geometry kernel**: geom/ (mesh IO, repair, booleans, BVH, raster, loft, hull, solidify, subsurf).
"""


def _doc(node):
    d = ast.get_docstring(node, clean=True)
    return d.strip() if d else ''


def _first_para(d, n=FIRST):
    p = re.split(r'\n\s*\n', d, maxsplit=1)[0] if d else ''
    p = ' '.join(p.split())
    return p if len(p) <= n else p[:n - 3].rsplit(' ', 1)[0] + ' ...'


def _first_line(d, n=LINE):
    """a docstring's first paragraph in one line, cut at its first sentence's end when that fits, else at a word."""
    s = ' '.join(re.split(r'\n\s*\n', d or '', maxsplit=1)[0].split())
    if len(s) <= n:
        return s
    i = s.find('. ')
    if 0 < i < n:
        return s[:i + 1]
    return s[:n - 4].rsplit(' ', 1)[0] + ' ...'


def _sig(node, n=72):
    """a function's arguments as written (defaults kept), cut to n characters."""
    try:
        a = ast.unparse(node.args)
    except Exception:
        return '...'
    return a if len(a) <= n else a[:n - 4].rsplit(',', 1)[0] + ', ...'


def _lit(n):
    try:
        if isinstance(n, ast.Call) and getattr(n.func, 'id', None) == 'dict':
            return {k.arg: _lit(k.value) for k in n.keywords}
        if isinstance(n, (ast.List, ast.Tuple)):
            return [_lit(x) for x in n.elts]
        return ast.literal_eval(n)
    except (ValueError, TypeError):
        return None


def modules(root=ROOT):
    """every charkit module (package, relative path) under the PACKAGES, sorted."""
    kit = os.path.join(root, 'charkit')
    out = []
    for pkg in PACKAGES:
        d = os.path.join(kit, pkg)
        if not os.path.isdir(d):
            continue
        for f in sorted(os.listdir(d)):
            if f.endswith('.py') and f != '__main__.py':
                out.append((pkg, os.path.relpath(os.path.join(d, f), root)))
    return out


def read(root, rel):
    """a module's map: its docstring's opening, public functions and classes (first docstring lines), QA parts,
    calibration entries, declared checks, measurement steps -> dict."""
    src = open(os.path.join(root, rel), encoding='utf-8').read()
    try:
        tree = ast.parse(src)
    except SyntaxError as e:
        return dict(rel=rel, doc='(does not parse: %s)' % e, defs=[], parts=[], cal=[], declared=[], steps=0)
    out = dict(rel=rel, doc=_first_para(_doc(tree)), defs=[], parts=[], cal=[], declared=[], steps=0,
               lines=src.count('\n') + 1)
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            for dec in getattr(node, 'decorator_list', ()):
                f = dec.func if isinstance(dec, ast.Call) else None
                name = getattr(f, 'id', None) or getattr(f, 'attr', None)
                if name == 'qa_part' and dec.args:
                    kw = {k.arg: _lit(k.value) for k in dec.keywords}
                    out['parts'].append(dict(name=_lit(dec.args[0]), order=kw.get('order'), prefix=kw.get('prefix') or '',
                                             table=kw.get('table'), fn=node.name))
            if node.name.startswith('_'):
                continue
            kind = 'class' if isinstance(node, ast.ClassDef) else 'def'
            out['defs'].append((kind, node.name if kind == 'class' else '%s(%s)' % (node.name, _sig(node)),
                                _first_line(_doc(node))))
        elif isinstance(node, ast.Assign):
            for t in node.targets:
                tid = getattr(t, 'id', None)
                if tid == 'CALIBRATION':
                    out['cal'] = [e for e in (_lit(node.value) or ()) if isinstance(e, dict)]
                elif tid == 'DECLARED_CHECKS':
                    out['declared'] = [e for e in (_lit(node.value) or ()) if isinstance(e, dict)]
                elif tid == 'MEASUREMENT_STEPS':
                    out['steps'] = len(_lit(node.value) or ())
    return out


def commands(root=ROOT):
    """the command line's commands: `python -m charkit CMD` -> the module it calls (cli.main's dispatch, read with ast)
    -> [(command, module)]."""
    src = open(os.path.join(root, 'charkit', 'cli.py'), encoding='utf-8').read()
    tree = ast.parse(src)
    out = []
    for fn in ast.walk(tree):
        if not (isinstance(fn, ast.FunctionDef) and fn.name == 'main'):
            continue
        for node in ast.walk(fn):
            if isinstance(node, ast.If) and isinstance(node.test, ast.Compare) and \
                    getattr(node.test.left, 'id', None) == 'cmd' and node.test.comparators and \
                    isinstance(node.test.comparators[0], ast.Constant):
                cmd = node.test.comparators[0].value
                mod = None
                for st in node.body:
                    if isinstance(st, ast.ImportFrom) and st.names:
                        mod = st.names[0].name
                        break
                    if isinstance(st, ast.Expr) and isinstance(st.value, ast.Call) and \
                            isinstance(st.value.func, ast.Name):
                        mod = 'cli.%s' % st.value.func.id
                        break
                out.append((cmd, mod or 'cli'))
    return sorted(set(out))


def generate(root=ROOT):
    """the map's text for a tree."""
    M = [(pkg, read(root, rel)) for pkg, rel in modules(root)]
    L = [HEADER, '## QA parts (registry order)', '',
         'A check named `PREFIX + name` comes from its part\'s function; `python -m charkit qa BUNDLE` runs them all.', '',
         '| order | part | check prefix | table | function |', '|---|---|---|---|---|']
    parts = sorted(((p['order'] or 0, p['name'], p['prefix'], p['table'], '%s:%s' % (m['rel'], p['fn']))
                    for _, m in M for p in m['parts']), key=lambda x: (x[0], x[1]))
    L += ['| %s | `%s` | %s | %s | `%s` |' % (o, n, '`%s`' % pre if pre else '-', t or '-', f)
          for o, n, pre, t, f in parts]
    L += ['', '## Commands (`python -m charkit CMD`)', '', '| command | module |', '|---|---|']
    try:
        L += ['| `%s` | `%s` |' % (c, m) for c, m in commands(root)]
    except (OSError, SyntaxError):
        L.append('| (charkit/cli.py unreadable) | |')
    cal = [(m['rel'], e) for _, m in M for e in m['cal']]
    if cal:
        L += ['', '## Calibration entries (charkit/calib/*.py; `python -m charkit calibrate list`)', '',
              '| module | check | part | adapter | known-bad |', '|---|---|---|---|---|']
        L += ['| `%s` | `%s` | %s | %s | %s |' % (os.path.basename(r), e.get('check'), e.get('part'), e.get('adapter'),
                                                e.get('known_bad') or '-') for r, e in cal]
    dec = [(m['rel'], d) for _, m in M for d in m['declared']]
    if dec:
        L += ['', '## Declared checks (charkit/declared.py)', '', '| module | check | family | piece | part | limits |',
              '|---|---|---|---|---|---|']
        L += ['| `%s` | `%s` | %s | %s | %s | %s |' % (os.path.basename(r), d.get('check'), d.get('family'), d.get('piece'),
                                                     d.get('part', 'declared'), d.get('limits')) for r, d in dec]
    L += ['', '## Modules', '']
    for pkg in PACKAGES:
        sec = [m for p, m in M if p == pkg]
        if not sec:
            continue
        L += ['### charkit/%s' % (pkg + '/' if pkg else ''), '']
        for m in sec:
            tags = []
            if m['parts']:
                tags.append('QA parts: ' + ', '.join('`%s`' % p['name'] for p in m['parts']))
            if m['steps']:
                tags.append('%d measurement steps' % m['steps'])
            if m['cal']:
                tags.append('%d calibration entries' % len(m['cal']))
            if m['declared']:
                tags.append('%d declared checks' % len(m['declared']))
            L.append('#### `%s`%s' % (m['rel'], (' (%s)' % '; '.join(tags)) if tags else ''))
            L.append('')
            if m['doc']:
                L += [m['doc'], '']
            if m['defs']:
                L += ['- %s`%s`%s' % ('class ' if k == 'class' else '', n, (': ' + d) if d else '')
                      for k, n, d in m['defs']]
                L.append('')
    return '\n'.join(L).rstrip() + '\n'


def main(args):
    if args and args[0] in ('-h', '--help'):
        print(__doc__)
        return 0
    opt = lambda k, d=None: args[args.index(k) + 1] if k in args else d
    root = os.path.abspath(os.path.expanduser(opt('--root', ROOT)))
    out = opt('--out') or os.path.join(root, OUT)
    text = generate(root)
    if '--check' in args:
        have = open(out).read() if os.path.exists(out) else ''
        print('%s: %s' % (out, 'current' if have == text else 'stale (regenerate: python -m charkit.codemap)'))
        return 0 if have == text else 1
    open(out, 'w').write(text)
    print('%s: %d lines' % (out, text.count('\n')))
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
