"""The announcer inventory: every clip's words, phones and syllables (Whisper word stamps, refined by wav2vec2 phoneme CTC
forced alignment on a hand lexicon), per-syllable nucleus times and F0 (hf0), loudness and the reverb-tail end; then a
phone inventory (phone -> best source spans, with pitch and HNR).
    .venv/bin/python projects/so-back/vocals/inventory.py      # -> vocals/inventory.json, vocals/INVENTORY.md
Needs W/stt_turbo.json, W/stt_small.en.json, W/stt_medium.en.json (stt_all.py)."""
import os, json, sys
import numpy as np, parselmouth
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from common import *
from hf0 import hf0
from lexicon import ipa_words, VOWELS, LEX, words_of
import phones

def f0_track(x):
    t, f, sc, v = hf0(x, SR, hop=0.005, fmin=85, fmax=480)
    return t, f, v

def f0_span(tr, a, b):
    t, f, v = tr
    k = v & (t >= a) & (t <= b)
    if k.sum() < 2: return None
    return dict(med=round(float(np.median(f[k])), 1), start=round(float(f[k][0]), 1), end=round(float(f[k][-1]), 1),
                voiced=round(float(k.mean() if k.size else 0), 2))

def hnr_span(x, a, b):
    i, j = int(a * SR), int(b * SR)
    if j - i < int(0.03 * SR): return None
    try:
        h = parselmouth.Sound(x[i:j], SR).to_harmonicity_cc(0.005, 75, 0.1, 1.0)
        v = h.values[0]; v = v[v > -100]
        return round(float(np.mean(v)), 1) if len(v) else None
    except Exception:
        return None

def syllabify(wphones):
    """wphones: [(phone, t0, t1, score)] of one word -> syllables [(label, t0, t1, nucleus_t0, nucleus_t1)]."""
    vi = [i for i, p in enumerate(wphones) if p[0] in VOWELS]
    if not vi: return []
    cuts = [0]
    for a, b in zip(vi, vi[1:]):
        n = b - a - 1
        cuts.append(a + 1 if n == 0 else (b if n == 1 else a + 2))
    cuts.append(len(wphones))
    out = []
    for k, v in enumerate(vi):
        seg = wphones[cuts[k]:cuts[k + 1]]
        out.append((''.join(p[0] for p in seg), seg[0][1], seg[-1][2], wphones[v][1], wphones[v][2]))
    return out

def analyse(key, stt):
    r = REG[key]; x = load(key)
    on, te = onset(x), tail_end(x)
    act = x[int(on * SR):int(te * SR) + 1]
    tr = f0_track(x)
    item = dict(key=key, path=r['path'], text=r['text'], dur=round(len(x) / SR, 3), onset=round(on, 3),
                tail_end=round(te, 3), rms_db=round(db(act), 1), peak_db=round(20 * np.log10(np.abs(x).max() + 1e-9), 1),
                stt={m: s.get(r['path'], {}).get('text') for m, s in stt.items()},
                whisper_words=stt['turbo'].get(r['path'], {}).get('words'))
    text = r['text']
    try:
        ws = ipa_words(text) if text and not text.startswith('(') else None
    except KeyError as e:
        ws = None; item['note'] = f'no lexicon entry for {e}'
    if ws:
        lp = phones.logprobs(x, SR)
        flat = [p for _, ps in ws for p in ps]
        al = phones.align(lp, ' '.join(flat))
        item['align_score'] = round(float(np.mean([a[3] for a in al])), 3)
        words, i = [], 0
        for w, ps in ws:
            wp = al[i:i + len(ps)]; i += len(ps)
            syl = []
            for lab, a, b, na, nb in syllabify(wp):
                syl.append(dict(syl=lab, t0=a, t1=b, nucleus=[na, nb], f0=f0_span(tr, na, nb)))
            words.append(dict(word=w, t0=wp[0][1], t1=wp[-1][2], phones=[list(p) for p in wp], syllables=syl))
        item['words'] = words
    return item

def main():
    stt = {m: json.load(open(f'{W}/stt_{m}.json')) for m in ('turbo', 'small.en', 'medium.en')
           if os.path.exists(f'{W}/stt_{m}.json')}
    items = []
    for key in REG:
        items.append(analyse(key, stt)); print(key, items[-1]['text'], items[-1].get('align_score'), flush=True)
    # phone inventory from the aligned US clips
    inv = {}
    for it in items:
        if 'words' not in it: continue
        x = load(it['key']); tr = f0_track(x)
        for w in it['words']:
            for p, a, b, s in w['phones']:
                inv.setdefault(p, []).append(dict(src=it['key'], word=w['word'], t0=a, t1=b, dur=round(b - a, 3),
                                                  score=s, f0=(f0_span(tr, a, b) or {}).get('med'), hnr=hnr_span(x, a, b)))
    best = {p: sorted(v, key=lambda d: -(d['score'] * min(d['dur'], 0.15)))[:6] for p, v in inv.items()}
    jdump(dict(clips=items, phones=best), os.path.join(HERE, 'inventory.json'))
    write_md(items, best)

def write_md(items, best):
    L = ['# Announcer inventory (SO BACK)', '',
         'Generated by `inventory.py`. Sources: the Melee announcer banks decoded by the GENO work (US 1.02 disc, 12 kHz mono), '
         'read from `~/games/melee/work/announcer/`. Times are seconds in the source clip. Word/phone boundaries: wav2vec2 '
         'phoneme CTC forced alignment on a hand lexicon (20 ms frames, so +-20 ms); Whisper turbo word stamps are kept in '
         '`inventory.json` for cross-checking. F0: `hf0.py` median over the vowel nucleus (reverberant, shouted voice: +-1 st).',
         '', '| key | text | dur | onset | tail end | RMS dB | STT turbo / small / medium | syllables (nucleus s @ F0 Hz) | align |',
         '|---|---|---|---|---|---|---|---|---|']
    for it in items:
        if it['key'].startswith('jp_'): continue
        syl = ' '.join(f"{s['syl']}({s['nucleus'][0]:.2f}@{(s['f0'] or {}).get('med', '-')})"
                       for w in it.get('words', []) for s in w['syllables'])
        st = ' / '.join(str(it['stt'].get(m)) for m in ('turbo', 'small.en', 'medium.en'))
        L.append(f"| {it['key']} | {it['text']} | {it['dur']:.2f} | {it['onset']:.2f} | {it['tail_end']:.2f} | "
                 f"{it['rms_db']} | {st} | {syl} | {it.get('align_score', '-')} |")
    L += ['', '## Japanese name bank (nr_name_jp): STT only', '', '| key | STT turbo | dur |', '|---|---|---|']
    for it in items:
        if it['key'].startswith('jp_'):
            L.append(f"| {it['key']} | {it['stt'].get('turbo')} | {it['dur']:.2f} |")
    L += ['', '## Phone inventory (best 6 spans per phone: alignment score x length)', '',
          '| phone | spans: src word t0-t1 (F0 Hz, HNR dB, score) |', '|---|---|']
    for p in sorted(best):
        L.append(f"| {p} | " + '; '.join(f"{d['src']} {d['word']} {d['t0']:.2f}-{d['t1']:.2f} ({d['f0']}, {d['hnr']}, {d['score']})"
                                          for d in best[p]) + ' |')
    open(os.path.join(HERE, 'INVENTORY.md'), 'w').write('\n'.join(L) + '\n')

if __name__ == '__main__':
    main()
